language: php

sudo: false

php:
  - "5.5"
  - "hhvm"

matrix:
  include:
    - php: "5.5"
      env: CHECKSTYLE="YES"
    - php: "7.0"
      env: COVERAGE="YES"
  allow_failures:
    - php: "hhvm"

cache:
  directories:
    - $HOME/.composer/cache

install: composer install

script: ./vendor/bin/ci-runner
